#pragma once

#include <QString>

#include <vector>

static std::unordered_map<QString, QString> properFeatureNames = {
    {"Morphology?", "Morphology Available"},
    {"has ephys", "Ephys Available"},
    {"marker_sum_norm_label", "Marker Sum Norm"},
    {"Norm_Marker_Sum.0.4_label", "Norm Marker Sum 0.4"},
    {"tree_class", "Class"},
    {"age_label", "Age"},
    {"gender_label", "Gender"},
    {"roi_label", "ROI"},
    {"structure", "Structure"},
    {"lobe", "lobe"},
    {"medical_conditions_label", "Medical Conditions"},
    {"input_resistance_ss", "Input Resistance SS"},
    {"downstroke_short_square", "Downstroke Short Sqr"},
    {"apical_dendrite_soma_percentile_y", "Soma Percentile Y (AD)"},
    {"width_short_square", "Width Short Square"},
    {"HANN_subclass_label_assignment_winner", "Subclass"},
    {"HANN_cluster_label_assignment_winner", "Cluster"},
    {"subclass_label_Hierarchical", "Subclass"},
    {"cluster_label_Hierarchical", "Supertype"},
    {"Subclass", "Subclass"},
    {"T-type", "Cluster"},
    {"Subclass_Hierarchical", "Subclass"},
    {"Group_Hierarchical", "Group"},
    {"Subclass_name", "Subclass"},
    {"Group_name", "Group"},
    {"cell_id", "Cell ID"},
    {"threshold_v_short_square", "Thresh V Short Sqr"},
    {"peak_freq_chirp", "Peak Freq Chirp"},
    {"cell_name_label", "Cell Name"},
    {"total_inductive_phase_chirp", "Total Inductive Phase Chirp"},
    {"paradigm", "paradigm"},
    {"basal_dendrite_frac_intersect_apical_dendrite", "Frac Intersect (BD w/ AD)"},
    {"fi_fit_slope", "FI Fit Slope"},
    {"fast_trough_v_rheo", "Fast Trough V Rheo"},
    {"upstroke_downstroke_ratio_short_square", "Upstroke Downstroke Ratio Short Sqr"},
    {"trough_v_rheo", "Trough V Rheo"},
    {"apical_dendrite_depth_pc_0", "Depth PC 0 (AD)"},
    {"sag_depol", "Sag Depol"},
    {"axon_exit_theta", "Axon Exit Theta"},
    {"fast_trough_v_hero", "Fast Trough V Hero"},
    {"upstroke_short_square", "Upstroke Short Sqr"},
    {"isi_cv_mean", "ISI CV Mean"},
    {"sag_area", "Sag Area"},
    {"apical_dendrite_extent_y", "Extent Y (AD)"},
    {"width_suprathresh_short_square", "Width Suprathresh Short Sqr"},
    {"threshold_v_hero", "Threshold V Hero"},
    {"sag", "Sag"},
    {"sync_freq_chirp", "Sync Freq Chirp"},
    {"peak_deltav_short_square", "Peak DeltaV Short Square"},
    {"axon_exit_distance", "Axon Exit Dist"},
    {"sag_tau", "Sag Tau"},
    {"v_baseline", "V Baseline"},
    {"adp_v_last_rheo", "ADP V Last Rheo"},
    {"postap_slope_rheo", "PostAP Slope Rheo"},
    {"rheobase_i", "Rheobase I"},
    {"vm_for_sag", "VM for Sag"},
    {"ir_late_mean", "IR Late Mean"},
    {"input_resistance", "Input Resistance"},
    {"avg_rate_max", "Avg Rate Max"},
    {"tau", "Tau"},
    {"width_suprathresh_hero", "Width Suprathresh Hero"},
    {"downstroke_adapt_ratio", "Downstroke Adapt Ratio"},
    {"downstroke_hero", "Downstroke Hero"},
    {"latency_rheo", "Latency Rheo"},
    {"avg_rate_rheo", "Avg Rate Rheo"},
    {"upstroke_hero", "Upstroke Hero"},
    {"width_adapt_ratio", "Width Adapt Ratio"},
    {"postap_slope_hero", "PostAP Slope Hero"},
    {"peak_v_hero", "Peak V Hero"},
    {"basal_dendrite_num_branches", "Num Branches (BD)"},
    {"mean_isi_rheo", "Mean ISI Rheo"},
    {"adapt_mean", "Adapt Mean"},
    {"downstroke_rheo", "Downstroke Rheo"},
    {"upstroke_downstroke_ratio_rheo", "Upstroke Downstroke Ratio Rheo"},
    {"threshold_v_rheo", "Threshold V Rheo"},
    {"apical_dendrite_depth_pc_1", "Depth PC 1 (AD)"},
    {"peak_v_rheo", "Peak V Rheo"},
    {"width_rheo", "Width Rheo"},
    {"median_isi_hero", "Median ISI Hero"},
    {"upstroke_rheo", "Upstroke Rheo"},
    {"width_suprathresh_rheo", "Width Suprathresh Rheo"},
    {"fast_trough_v_last_rheo", "Fast Trough V Last Rheo"},
    {"adapt_hero", "Adapt Hero"},
    {"avg_rate_hero", "Avg Rate Hero"},
    {"latency_hero", "Latency Hero"},
    {"mean_isi_hero", "Mean ISI Hero"},
    {"isi_cv_hero", "ISI CV Hero"},
    {"ir_late_hero", "IR Late Hero"},
    {"upstroke_downstroke_ratio_hero", "Upstroke Downstroke Ratio Hero"},
    {"width_hero", "Width Hero"},
    {"apical_dendrite_soma_percentile_x", "Soma Percentile X (AD)"},
    {"upstroke_ramp", "Upstroke Ramp"},
    {"trough_v_hero", "Trough V Hero"},
    {"ahp_delay_ratio_hero", "AHP Delay Ratio Hero"},
    {"sag_area_depol", "Sag Area Depol"},
    {"sag_tau_depol", "Sag Tau Depol"},
    {"isi_adapt_ratio", "ISI Adapt Ratio"},
    {"upstroke_adapt_ratio", "Upstroke Adapt Ratio"},
    {"peak_v_adapt_ratio", "Peak V Adapt Ratio"},
    {"threshold_v_adapt_ratio", "Threshold V Adapt Ratio"},
    {"ahp_delay_ratio_5spike", "AHP Delay Ratio 5-Spike"},
    {"trough_slowdeltav_rheo", "Trough Slow DeltaV Rheo"},
    {"trough_slowdeltav_hero", "Trough Slow DeltaV Hero"},
    {"fast_trough_deltav_rheo", "Fast Trough DeltaV Rheo"},
    {"fast_trough_deltav_hero", "Fast Trough DeltaV Hero"},
    {"peak_deltav_rheo", "Peak DeltaV Rheo"},
    {"width_suprathresh_ramp", "Width Suprathresh Ramp"},
    {"peak_deltav_hero", "Peak DeltaV Hero"},
    {"first_isi_inv_rheo", "First ISI Inv Rheo"},
    {"first_isi_inv_hero", "First ISI Inv Hero"},
    {"upstroke_downstroke_ratio_ramp", "Upstroke Downstroke Ratio Ramp"},
    {"threshold_v_ramp", "Threshold V Ramp"},
    {"width_ramp", "Width Ramp"},
    {"downstroke_ramp", "Downstroke Ramp"},
    {"trough_v_ramp", "Trough V Ramp"},
    {"threshold_i_ramp", "Threshold I Ramp"},
    {"apical_dendrite_depth_pc_2", "Depth PC 2 (AD)"},
    {"postap_slope_ramp", "PostAP Slope Ramp"},
    {"fast_trough_deltav_ramp", "Fast Trough DeltaV Ramp"},
    {"peak_deltav_ramp", "Peak DeltaV Ramp"},
    {"peak_ratio_chirp", "Peak Ratio Chirp"},
    {"basal_dendrite_bias_y", "Bias Y (BD)"},
    {"3db_freq_chirp", "3dB Freq Chrip"},
    {"peak_impedance_chirp", "Peak Impedance Chirp"},
    {"low_freq_impedance_chirp", "Low-freq Impedance Chirp"},
    {"phase_low_chirp", "Phase Low Chirp"},
    {"phase_peak_chirp", "Phase Peak Chirp"},
    {"apical_dendrite_bias_x", "Bias X (AD)"},
    {"apical_dendrite_bias_y", "Bias Y (AD)"},
    {"apical_dendrite_depth_pc_3", "Depth PC 3 (AD)"},
    {"apical_dendrite_early_branch_path", "Early Branch Path (AD)"},
    {"apical_dendrite_emd_with_basal_dendrite", "Emd w/ BD (AD)"},
    {"apical_dendrite_extent_x", "Extent X (AD)"},
    {"apical_dendrite_frac_above_basal_dendrite", "Frac Above BD (AD)"},
    {"apical_dendrite_frac_below_basal_dendrite", "Frac Below BD (AD)"},
    {"apical_dendrite_frac_intersect_basal_dendrite", "Frac Intersect BD (AD)"},
    {"apical_dendrite_max_branch_order", "Max Branch Order (AD)"},
    {"apical_dendrite_max_euclidean_distance", "Max Euclidean Dist (AD)"},
    {"apical_dendrite_max_path_distance", "Max Path Dist (AD)"},
    {"apical_dendrite_mean_contraction", "Mean Contraction (AD)"},
    {"apical_dendrite_mean_diameter", "Mean Diameter (AD)"},
    {"apical_dendrite_mean_moments_along_max_distance_projection", "Mean Moments Along Max Dist Proj (AD)"},
    {"apical_dendrite_num_branches", "Num Branches (AD)"},
    {"apical_dendrite_num_outer_bifurcations", "Num Outer Bifurcations (AD)"},
    {"apical_dendrite_std_moments_along_max_distance_projection", "Std Moments Along Max Dist Proj (AD)"},
    {"apical_dendrite_total_length", "Total Length (AD)"},
    {"apical_dendrite_total_surface_area", "Total Surface Area (AD)"},
    {"basal_dendrite_bias_x", "Bias X (BD)"},
    {"basal_dendrite_calculate_number_of_stems", "Calculate Number of Stems (BD)"},
    {"basal_dendrite_extent_x", "Extent X (BD)"},
    {"basal_dendrite_extent_y", "Extent Y (BD)"},
    {"basal_dendrite_frac_above_apical_dendrite", "Frac Above AD (BD)"},
    {"basal_dendrite_frac_below_apical_dendrite", "Frac Below AD (BD)"},
    {"basal_dendrite_max_branch_order", "Max Branch Order (BD)"},
    {"basal_dendrite_max_euclidean_distance", "Max Euclidean Dist (BD)"},
    {"basal_dendrite_max_path_distance", "Max Path Dist (BD)"},
    {"basal_dendrite_mean_contraction", "Mean Contraction (BD)"},
    {"basal_dendrite_mean_diameter", "Mean Diameter (BD)"},
    {"basal_dendrite_soma_percentile_x", "Soma Percentile X (BD)"},
    {"basal_dendrite_soma_percentile_y", "Soma Percentile Y (BD)"},
    {"basal_dendrite_stem_exit_down", "Stem Exit Down (BD)"},
    {"basal_dendrite_stem_exit_side", "Stem Exit Side (BD)"},
    {"basal_dendrite_stem_exit_up", "Stem Exit Up (BD)"},
    {"basal_dendrite_total_length", "Total Length (BD)"},
    {"basal_dendrite_total_surface_area", "Total Surface Area (BD)"},
    {"soma_aligned_dist_from_pia", "Soma Aligned Dist From Pia"},
    {"soma_surface_area", "Soma Surface Area"}
};

static std::unordered_map<QString, QString> properMorphologyFeatureNames = {
    {"apical_dendrite_bias_x","horizontal apical bias"},
    {"apical_dendrite_bias_y","vertical apical bias"},
    {"apical_dendrite_depth_pc_0","apical depth pc 0"},
    {"apical_dendrite_depth_pc_1","apical depth pc 1"},
    {"apical_dendrite_depth_pc_2","apical depth pc 2"},
    {"apical_dendrite_depth_pc_3","apical depth pc 3"},
    {"apical_dendrite_depth_pc_4","apical depth pc 4"},
    {"apical_dendrite_early_branch_path","early apical branch path"},
    {"apical_dendrite_emd_with_basal_dendrite","apical EMD with basal"},
    {"apical_dendrite_extent_x","horizontal apical extent"},
    {"apical_dendrite_extent_y","vertical apical extent"},
    {"apical_dendrite_frac_above_basal_dendrite","fraction of apical above basal"},
    {"apical_dendrite_frac_below_basal_dendrite","fraction of apical below basal"},
    {"apical_dendrite_frac_intersect_basal_dendrite","fraction of apical intersecting with basal"},
    {"apical_dendrite_max_branch_order","max apical branch order"},
    {"apical_dendrite_max_euclidean_distance","max apical euclidean distance"},
    {"apical_dendrite_max_path_distance","max apical path distance"},
    {"apical_dendrite_mean_contraction","mean apical contraction"},
    {"apical_dendrite_mean_diameter","mean apical diameter"},
    {"apical_dendrite_mean_moments_along_max_distance_projection","mean moments along apical max distance projection"},
    {"apical_dendrite_num_branches","number of apical branches"},
    {"apical_dendrite_num_outer_bifurcations","number of apical outer bifurcations"},
    {"apical_dendrite_soma_percentile_x","horizontal apical soma percentile"},
    {"apical_dendrite_soma_percentile_y","vertical apical soma percentile"},
    {"apical_dendrite_std_moments_along_max_distance_projection","std moments along apical max distance projection"},
    {"apical_dendrite_total_length","total apical length"},
    {"apical_dendrite_total_surface_area","total apical surface area"},
    {"axon_exit_distance","axon exit distance"},
    {"axon_exit_theta","axon exit theta"},
    {"basal_dendrite_bias_x","horizontal basal bias"},
    {"basal_dendrite_bias_y","vertical basal bias"},
    {"basal_dendrite_calculate_number_of_stems","number basal stems exiting soma"},
    {"basal_dendrite_extent_x","horizontal basal extent"},
    {"basal_dendrite_extent_y","vertical basal extent"},
    {"basal_dendrite_frac_above_apical_dendrite","fraction of basal above apical"},
    {"basal_dendrite_frac_below_apical_dendrite","fraction of basal below apical"},
    {"basal_dendrite_frac_intersect_apical_dendrite","fraction of basal intersecting with apical"},
    {"basal_dendrite_max_branch_order","max basal branch order"},
    {"basal_dendrite_max_euclidean_distance","max basal euclidean distance"},
    {"basal_dendrite_max_path_distance","max basal path distance"},
    {"basal_dendrite_mean_contraction","mean basal contraction"},
    {"basal_dendrite_mean_diameter","mean basal diameter"},
    {"basal_dendrite_num_branches","number of basal branches"},
    {"basal_dendrite_soma_percentile_x","horizontal basal soma percentile"},
    {"basal_dendrite_soma_percentile_y","vertical basal soma percentile"},
    {"basal_dendrite_stem_exit_down","basal stem exit down"},
    {"basal_dendrite_stem_exit_side","basal stem exit side"},
    {"basal_dendrite_stem_exit_up","basal stem exit up"},
    {"basal_dendrite_total_length","basal total length"},
    {"basal_dendrite_total_surface_area","basal total surface area"},
    {"soma_aligned_dist_from_pia","soma aligned distance from pia"},
    {"soma_surface_area","soma surface area"}
};

static std::unordered_map<QString, QString> properMorphologyFeatureNamesBG = {
    {"23_Sholl_PC0","neurite Sholl pc 0"},
    {"23_Sholl_PC1","neurite Sholl pc 1"},
    {"2_Sholl_PC0","axon Sholl pc 0"},
    {"2_Sholl_PC1","axon Sholl pc 1"},
    {"3_Sholl_PC0","dendrite Sholl pc 0"},
    {"3_Sholl_PC1","dendrite Sholl pc 1"},
    {"axon_bias_dorsal","vertical axon bias"},
    {"axon_bias_medial","horizontal axon bias"},
    {"axon_exit_distance","axon exit distance"},
    {"axon_exit_theta_coronal","axon exit theta"},
    {"axon_extent_dorsal","vertical axon extent"},
    {"axon_extent_medial","horizontal axon extent"},
    {"axon_max_branch_order","max axon branch order"},
    {"axon_max_euclidean_distance","max axon euclidean distance"},
    {"axon_max_path_distance","max axon path distance"},
    {"axon_mean_contraction","mean axon contraction"},
    {"axon_num_branches","number of axon branches"},
    {"axon_soma_percentile_dorsal","vertical axon soma percentile"},
    {"axon_soma_percentile_medial","horizontal axon soma percentile"},
    {"axon_total_length","axon total length"},
    {"basal_dendrite_bias_dorsal","vertical basal bias"},
    {"basal_dendrite_bias_medial","horizontal basal bias"},
    {"basal_dendrite_calculate_number_of_stems","number basal stems exiting soma"},
    {"basal_dendrite_extent_dorsal","vertical basal extent"},
    {"basal_dendrite_extent_medial","horizontal basal extent"},
    {"basal_dendrite_max_branch_order","max basal branch order"},
    {"basal_dendrite_max_euclidean_distance","max basal euclidean distance"},
    {"basal_dendrite_max_path_distance","max basal path distance"},
    {"basal_dendrite_mean_contraction","mean basal contraction"},
    {"basal_dendrite_mean_diameter","mean basal diameter"},
    {"basal_dendrite_num_branches","number of basal branches"},
    {"basal_dendrite_soma_percentile_dorsal","vertical basal soma percentile"},
    {"basal_dendrite_soma_percentile_medial","horizontal basal soma percentile"},
    {"basal_dendrite_stem_exit_MedialLateral","basal stem exit medial/lateral"},
    {"basal_dendrite_stem_exit_dorsal","basal stem exit dorsal"},
    {"basal_dendrite_stem_exit_ventral","basal stem exit ventral"},
    {"basal_dendrite_total_length","basal total length"},
    {"basal_dendrite_total_surface_area","basal total surface area"},
    {"soma_surface_area","soma surface area"}
};

static std::unordered_map<QString, QString> properEphysFeatureNames = {
    {"combined_upstroke_downstroke_ratio_rheo","AP up/down ratio"},
    {"combined_width_rheo","AP width (ms)"},
    {"combined_upstroke_rheo","AP ustroke"},
    {"combined_downstroke_rheo","AP downstroke"},
    {"combined_sag","Sag"},
    {"combined_baseline","Resting membrane potential (RMP)"},
    {"combined_input_resistance_SS","Input resistance"},
    {"combined_tau","Tau"},
    {"combined_peak_v","AP peak"},
    {"combined_trough_v_rheo","Trough voltage"},
    {"combined_fast_trough_v_rheo","Fast trough voltage"},
    {"combined_peak_freq_chirp","Chirp peak"},
    {"combined_AP_threshold","AP threshold"},
    {"combined_peak_impedance_chirp","ZAP (peak impedance)"},
    {"sm_rheobase_i","Rheobase current"},
    {"sm_fi_fit_slope","FI slope"},
    {"sm_latency_rheo","Latency"},
    {"sm_avg_rate_hero","Avg spike rate"},
    {"sm_mean_isi_hero","Mean ISI"},
    {"sm_isi_adapt_ratio","ISI adaptation ratio"},
    {"sm_trough_slowdeltav_hero","Slow trough absolute voltage"},
    {"sm_fast_trough_deltav_hero","Fast trough absolute voltage"},
    {"depth_from_pia_norm","Normalized depth from pia"},
    {"sm_adapt_mean","Adaptation mean"}
};

static std::unordered_map<QString, QString> properEphysFeatureNamesBG = {
    // Sweep features
    {"adapt","Adaptation Index"},
    {"avg_rate","Avg Firing Rate (Hz)"},
    {"latency","Latency (sec)"},
    {"first_isi_inv","Initial Firing Rate (Hz)"},
    {"first_isi","First Interspike Interval (ms)"},
    {"isi_cv","ISI Coefficient of Variation"},
    {"ir_late","Irregularity Ratio"},
    {"threshold_i","Slow Ramp Rheobase (pA)"},
    {"last_spike_t","Last Spike Time (sec)"},
    // AP features
    {"upstroke_downstroke_ratio","Upstroke/Downstroke"},
    {"threshold_v","AP Threshold (mV)"},
    {"peak_v","Peak of AP (mV)"},
    {"peak_deltav","AP Height (mV)"},
    {"trough_v","AP Trough (mV)"},
    {"trough_t","AP Trough Absolute Time (sec)"},
    {"trough_slowdeltav","AHP Slow (mV)"},
    {"width","AP Width (ms)"},
    {"upstroke","Upstroke (mV/ms)"},
    {"downstroke","Downstroke (mV/ms)"},
    {"width_suprathresh","Threshold AP Width (ms)"},
    {"fast_trough_v","AHP Fast V (mV)"},
    {"ahp_delay","AP Trough Time (sec)"},
    {"ahp_delay_ratio","AHP Delay Ratio"},
    {"postap_slope","ADP Rate (mV/ms)"},
    {"adp_v","ADP Voltage (mV)"},
    // Cross-sweep long square features
    {"input_resistance","Max Rin (MΩ)"},
    {"fi_fit_slope","f-I Slope (Hz/pA)"},
    {"v_baseline","Vrest (mV)"},
    {"rheobase_i","Rheobase (pA)"},
    {"tau","Membrane Time Constant / Tau (sec)"},
    {"sag","Sag Fraction"},
    {"sag_area","Sag Integral (mVs)"},
    {"sag_tau","Sag Time Constant (sec)"},
    {"sag_peak_t","Sag Delay (sec)"},
    {"sag_width","Sag Width (sec)"},
    {"input_resistance_ss","SS Rin (MΩ)"},
    {"vm_for_sag","Peak response for sag analysis"},
    // Chirp features
    {"peak_ratio","Resonance Strength / Q"},
    {"peak_freq","Resonance Frequency"},
    {"3db_freq","3 dB Cutoff (Hz)"},
    {"peak_impedance","Max Impedance"},
    {"low_freq_impedance","Low Freq Impedance"},
    {"sync_freq","Sync Frequency"},
    {"phase_peak","Phase Peak"},
    {"phase_low","Low Freq Phase"},
    {"total_inductive_phase","Inductive Phase"},
    // Actual features
    {"upstroke_downstroke_ratio_short_square","Upstroke/Downstroke Short Square"},
    {"threshold_v_short_square","AP Threshold (mV) Short Square"},
    {"width_short_square","AP Width (ms) Short Square"},
    {"upstroke_short_square","Upstroke (mV/ms) Short Square"},
    {"downstroke_short_square","Downstroke (mV/ms) Short Square"},
    {"width_suprathresh_short_square","Threshold AP Width (ms) Short Square"},
    {"AP_t_short_square",""},
    {"AP_v_short_square",""},
    {"peak_deltav_short_square","AP Height (mV) Short Square"},
    {"sag","Sag Fraction"},
    {"sag_area","Sag Integral (mVs)"},
    {"sag_tau","Sag Time Constant (sec)"},
    {"v_baseline",""},
    {"rheobase_i",""},
    {"fi_fit_slope",""},
    {"vm_for_sag","Peak response for sag analysis"},
    {"input_resistance","Max Rin (MΩ)"},
    {"input_resistance_ss","SS Rin (MΩ)"},
    {"tau","Membrane Time Constant / Tau (sec)"},
    {"full_fI",""},
    {"latency_rheo","Rheo Latency (sec)"},
    {"avg_rate_rheo","Rheo Avg Firing Rate (Hz)"},
    {"mean_isi_rheo",""},
    {"upstroke_downstroke_ratio_rheo",""},
    {"threshold_v_rheo",""},
    {"peak_v_rheo",""},
    {"width_rheo",""},
    {"upstroke_rheo","Upstroke (mV/ms) Rheo"},
    {"downstroke_rheo","Downstroke (mV/ms) Rheo"},
    {"width_suprathresh_rheo","Threshold AP Width (ms) Rheo"},
    {"trough_v_rheo","AP Trough (mV) Rheo"},
    {"trough_t_rheo","AP Trough Absolute Time (sec) Rheo"},
    {"fast_trough_v_rheo","AHP Fast V (mV) Rheo"},
    {"postap_slope_rheo","ADP Rate (mV/ms) Rheo"},
    {"fast_trough_v_last_rheo",""},
    {"adp_v_last_rheo","ADP Voltage (mV) Last Rheo"},
    {"adapt_hero","Adaptation Index Hero"},
    {"avg_rate_hero","Avg Firing Rate (Hz) Hero"},
    {"latency_hero","Latency (sec) Hero"},
    {"last_spike_t_hero","Last Spike Time (sec) Hero"},
    {"mean_isi_hero",""},
    {"median_isi_hero",""},
    {"isi_cv_hero","ISI Coefficient of Variation Hero"},
    {"ir_late_hero","Irregularity Ratio Hero"},
    {"upstroke_downstroke_ratio_hero","Upstroke/Downstroke Hero"},
    {"threshold_v_hero","AP Threshold (mV) Hero"},
    {"peak_v_hero","Peak of AP (mV) Hero"},
    {"width_hero","AP Width (ms) Hero"},
    {"upstroke_hero","Upstroke (mV/ms) Hero"},
    {"downstroke_hero","Downstroke (mV/ms) Hero"},
    {"width_suprathresh_hero","Threshold AP Width (ms) Hero"},
    {"trough_v_hero","AP Trough (mV) Hero"},
    {"trough_t_hero","AP Trough Absolute Time (sec) Hero"},
    {"fast_trough_v_hero","AHP Fast V (mV) Hero"},
    {"postap_slope_hero","ADP Rate (mV/ms) Hero"},
    {"ahp_delay_ratio_hero","AHP Delay Ratio Hero"},
    {"ahp_delay_hero","AP Trough Time (sec) Hero"},
    {"sag_depol",""},
    {"sag_area_depol",""},
    {"sag_tau_depol",""},
    {"adapt_mean","Mean Adaptation Index"},
    {"isi_cv_mean","Mean ISI Coefficient of Variation"},
    {"ir_late_mean","Mean Irregularity Ratio"},
    {"avg_rate_max","Max Avg Firing Rate (Hz)"},
    {"isi_adapt_ratio",""},
    {"width_adapt_ratio",""},
    {"upstroke_adapt_ratio",""},
    {"downstroke_adapt_ratio",""},
    {"threshold_v_adapt_ratio",""},
    {"peak_v_adapt_ratio",""},
    {"peak_deltav_adapt_ratio",""},
    {"peak_deltav_5th_adapt_ratio",""},
    {"ahp_delay_ratio_5spike",""},
    {"ahp_delay_5spike",""},
    {"trough_slowdeltav_rheo",""},
    {"trough_slowdeltav_hero",""},
    {"fast_trough_deltav_rheo",""},
    {"fast_trough_deltav_hero",""},
    {"peak_deltav_rheo",""},
    {"peak_deltav_hero",""},
    {"first_isi_inv_rheo",""},
    {"first_isi_inv_hero",""},
    {"upstroke_downstroke_ratio_ramp",""},
    {"threshold_v_ramp",""},
    {"width_ramp",""},
    {"upstroke_ramp",""},
    {"downstroke_ramp",""},
    {"width_suprathresh_ramp",""},
    {"AP_t_ramp",""},
    {"AP_v_ramp",""},
    {"trough_v_ramp","AP Trough (mV) Ramp"},
    {"threshold_i_ramp","Slow Ramp Rheobase (pA) Ramp"},
    {"postap_slope_ramp",""},
    {"fast_trough_deltav_ramp",""},
    {"peak_deltav_ramp",""},
    {"peak_ratio_chirp","Resonance Strength / Q Chirp"},
    {"peak_freq_chirp","Resonance Frequency Chirp"},
    {"3db_freq_chirp","3 dB Cutoff (Hz) Chirp"},
    {"peak_impedance_chirp","Max Impedance Chirp"},
    {"low_freq_impedance_chirp","Low Freq Impedance Chirp"},
    {"sync_freq_chirp","Sync Frequency Chirp"},
    {"phase_peak_chirp","Phase Peak Chirp"},
    {"phase_low_chirp","Low Freq Phase Chirp"},
    {"total_inductive_phase_chirp","Inductive Phase Chirp"}
};

static QStringList featuresToDelete = {
    "blowout_mv_qc",
    "electrode_0_pa_qc",
    "recording_date_qc",
    "seal_gohm_qc",
    "input_resistance_mohm_qc",
    "initial_access_resistance_mohm_qc",
    "input_access_resistance_ratio_qc",
    "fail_tags_qc",
    "failed_blowout",
    "failed_electrode_0",
    "failed_seal",
    "failed_input_access_resistance",
    "failed_qc",
    "failed_fx_long_squares",
    "failed_fx_short_squares",
    "failed_fx_ramps",
    "failed_fx_chirps",
    "failed_fx_sweep_features"
};
